setup: adiciona configurações para observability

diff --git a/.github/workflows/ci-infra.yml b/.github/workflows/ci-infra.yml
--- a/.github/workflows/ci-infra.yml
+++ b/.github/workflows/ci-infra.yml
@@ -1,21 +1,22 @@
 name: CI/CD — Terraform Infrastructure
 
 on:
-  # push:
-  #   branches: ["main", "develop"]
-  #   paths:
-  #     - "fase_4/tech_challenge/toggle-master-microservices/terraform/**"
-  # pull_request:
-  #   branches: ["main", "develop"]
-  #   paths:
-  #     - "fase_4/tech_challenge/toggle-master-microservices/terraform/**"
-  workflow_dispatch: # remover - adicionado só para setup inicial
+  push:
+    branches: ["main", "develop"]
+    paths:
+      - "fase_4/tech_challenge/toggle-master-microservices/terraform/**"
+  pull_request:
+    branches: ["main", "develop"]
+    paths:
+      - "fase_4/tech_challenge/toggle-master-microservices/terraform/**"
+  # workflow_dispatch: # remover - adicionado só para setup inicial
 
 env:
   TERRAFORM_DIR: fase_4/tech_challenge/toggle-master-microservices/terraform
   BACKEND_DIR: fase_4/tech_challenge/toggle-master-microservices/terraform/backend
   TERRAGRUNT_DIR: fase_4/tech_challenge/toggle-master-microservices/terraform/environments/dev
   K8S_SECRETS_DIR: fase_4/tech_challenge/toggle-master-microservices/k8s-secrets/dev
+  OBSERVABILITY_DIR: fase_4/tech_challenge/toggle-master-microservices/observability/dev
   EKS_DIR: fase_4/tech_challenge/toggle-master-microservices/eks
   TG_VERSION: "0.82.2"
   TOFU_VERSION: "1.10.1"
@@ -125,6 +126,7 @@ jobs:
         env:
           TF_VAR_AUTH_MASTER_KEY: ${{ secrets.AUTH_MASTER_KEY }}
           TF_VAR_EVALUATION_API_KEY: ${{ secrets.EVALUATION_API_KEY }}
+          TF_VAR_DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY}}
         run: |
           terragrunt run --all --terragrunt-non-interactive plan \
             -no-color 2>&1 | tee plan_output.txt
@@ -262,11 +264,77 @@ jobs:
           KUBE_HOST: "https://127.0.0.1:6443"
           KUBE_INSECURE: "true"
         run: terragrunt apply -auto-approve
+  
+  observability:
+    name: Apply — Observability
+    runs-on: ubuntu-latest
+    needs: k8s-secrets
+    if: github.event_name == 'push'
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Setup Terragrunt
+        uses: gruntwork-io/terragrunt-action@v3
+        with:
+          tg_version: ${{ env.TG_VERSION }}
+          tofu_version: ${{ env.TOFU_VERSION }}
+
+      - name: Get bastion IP and EKS endpoint
+        id: infra
+        run: |
+          BASTION_IP=$(aws ec2 describe-instances \
+            --filters \
+              "Name=tag:Name,Values=toggle-master-dev-bastion" \
+              "Name=instance-state-name,Values=running" \
+            --query 'Reservations[0].Instances[0].PublicIpAddress' \
+            --output text)
+
+          if [ -z "$BASTION_IP" ] || [ "$BASTION_IP" = "None" ]; then
+            echo "ERROR: Bastion IP not found."
+            exit 1
+          fi
+
+          EKS_ENDPOINT=$(aws eks describe-cluster \
+            --name toggle-master-eks \
+            --query 'cluster.endpoint' \
+            --output text | sed 's|https://||')
+
+          echo "bastion_ip=$BASTION_IP" >> $GITHUB_OUTPUT
+          echo "eks_endpoint=$EKS_ENDPOINT" >> $GITHUB_OUTPUT
+
+      - name: Save SSH key
+        run: |
+          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/iac-key.pem
+          chmod 400 /tmp/iac-key.pem
+
+      - name: Open SSH tunnel via bastion
+        run: |
+          ssh -i /tmp/iac-key.pem \
+            -o StrictHostKeyChecking=no \
+            -o ServerAliveInterval=60 \
+            -L 6443:${{ steps.infra.outputs.eks_endpoint }}:443 \
+            ubuntu@${{ steps.infra.outputs.bastion_ip }} \
+            -N -f
+          sleep 5
+
+      - name: Terragrunt apply — observability
+        working-directory: ${{ env.OBSERVABILITY_DIR }}
+        env:
+          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
+        run: terragrunt apply -auto-approve
 
   argocd-install:
     name: Install — ArgoCD
     runs-on: ubuntu-latest
-    needs: k8s-secrets
+    needs: observability
     if: github.event_name == 'push'
     steps:
       - uses: actions/checkout@v4
