infra: adiciona dd cluster agent

diff --git a/.github/workflows/ci-infra.yml b/.github/workflows/ci-infra.yml
--- a/.github/workflows/ci-infra.yml
+++ b/.github/workflows/ci-infra.yml
@@ -341,10 +341,16 @@ jobs:
         working-directory: ${{ env.OBSERVABILITY_DIR }}
         env:
           DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }} # Terragrunt
+          DATADOG_CLUSTER_AGENT_TOKEN: ${{ secrets. DATADOG_CLUSTER_AGENT_TOKEN }}
           TF_VAR_DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }} # Terraform
+          TF_VAR_DATADOG_CLUSTER_AGENT_TOKEN: ${{ secrets. DATADOG_CLUSTER_AGENT_TOKEN }}
         run: |
           if [ -z "${{ secrets.DATADOG_API_KEY }}" ]; then
             echo "ERROR: DATADOG_API_KEY vazio no GitHub Secrets"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DATADOG_CLUSTER_AGENT_TOKEN }}" ]; then
+            echo "ERROR: DATADOG_CLUSTER_AGENT_TOKEN vazio no GitHub Secrets"
             exit 1
           fi
           rm -rf .terragrunt-cache
